### ISSUE TITLE
download third_part lib failed

### ISSUE THREAD

**Issue by zhaojianpeerfintech** [bnb-chain/java-sdk#116]
下载依赖包失败
![image](https://user-images.githubusercontent.com/42340597/119106023-79e2f880-ba50-11eb-8510-c4e92e7c6153.png)

**Comment by huangshun666** [comment]
maven settings.xml
<mirror>
        <id>alimaven</id>
        <name>aliyun maven</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
        <mirrorOf>central</mirrorOf>
    </mirror>

**Comment by appfile01** [comment]
is there an update on this? sdk has been unusable since may for this reason.
