### ISSUE TITLE
[WARNING] The POM for org.ethereum:ethereumj-core:jar:1.12.0-RELEASE is missing, no dependency information available

### ISSUE THREAD

**Issue by ghost** [bnb-chain/java-sdk#123]
[WARNING] The POM for org.ethereum:ethereumj-core:jar:1.12.0-RELEASE is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.914 s
[INFO] Finished at: 2021-10-14T17:10:20+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project binance-dex-api-client: Could not resolve dependencies for project com.binance.dex.api:binance-dex-api-client:jar:1.1.2: Failure to find org.ethereum:ethereumj-core:jar:1.12.0-RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by atkmojo** [comment]
any updates about that ??

**Comment by appfile01** [comment]
bintray that hosted the jar file is down. project developers need to do something about this. Project is not compiling due to this file being missing.
