### ISSUE TITLE
Please add jar files shaded with all dependencies in the releases section.

### ISSUE THREAD

**Issue by ghost** [bnb-chain/java-sdk#124]
I'm tired of maven projects with has errors like this:
`[INFO] -------------< com.binance.dex.api:binance-dex-api-client >-------------
[INFO] Building binance-dex-api-client 1.1.2
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.ethereum:ethereumj-core:jar:1.12.0-RELEASE is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.845 s
[INFO] Finished at: 2021-11-28T07:03:15+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project binance-dex-api-client: Could not resolve dependencies for project com.binance.dex.api:binance-dex-api-client:jar:1.1.2: org.ethereum:ethereumj-core:jar:1.12.0-RELEAS>[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

Adding jar files in the [Releases](https://github.com/binance-chain/java-sdk/releases) will solve this problem.

**Comment by appfile01** [comment]
We need an update on this. as it stands now, the binance-java sdk is unusable as it won't compile due to the bintray-site where the ethereumj-core jar-file is hosted has been taken permanently down (in May!). Please do something about this.

**Comment by congatobu** [comment]
```xml

<repository>
            <id>jcenter</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>

```
add repository to pom

**Comment by appfile01** [comment]
I add this code where?

**Comment by appfile01** [comment]
In reality this whole thing should be updated to use newer versions?

**Comment by appfile01** [comment]
ok, adding repo seems to have worked, but I jhave my sincere doubts if it's safe.

**Comment by 100doses** [comment]
still no aswner, nice support

**Comment by 100doses** [comment]
> 

oh my bad didn't seen, can you give me the jar files with all depends ?
i'm tired of using maven, i want to add to classpath manually.
