### ISSUE TITLE
Bech32 format？

### ISSUE THREAD

**Issue by XiFYuW** [bnb-chain/java-sdk#127]
How do I convert an ETH address to a Bech32 address to request the project's interface?
For example: '0x810c73180147ab5b22e94a3a109a22354ca1d09e' convert 'tbnb1syx8xxqpg744kghffgappx3zx4x2r5y7v8ajmy' kind of address.

**Comment by leelovejava** [comment]
https://slowli.github.io/bech32-buffer/
