### ISSUE TITLE
Can't use api in gradle

### ISSUE THREAD

**Issue by orendayan** [bnb-chain/java-sdk#45]
Hi,
I try to get your API via android gradle and get an error while it try to sync
ERROR: Failed to resolve: com.binance.dex.api:binance-dex-api-client:1.0.0

the line that I added to gradle dependencies is:
    implementation 'com.binance.dex.api:binance-dex-api-client:1.0.0'

**Comment by geastwood** [comment]
Don't think they have it published on maven central (based on a quick examination on the `pom.xml`). Guess you have to use it locally.
