### ISSUE TITLE
How does the android project use this library

### ISSUE THREAD

**Issue by githubityu** [bnb-chain/java-sdk#75]
How does the android project use this library

**Comment by githubityu** [comment]
![image](https://user-images.githubusercontent.com/5370911/69392943-b24a2f00-0d12-11ea-95ea-e9916acffc16.png)

**Comment by githubityu** [comment]
上面的图片是在android项目下面生成的代码和java下面生成的不一样导致错误。

**Comment by FitzLu** [comment]
sdk 是用 maven 构建的，android 是用的 gradle，你可以先用支持 maven 构建的 IDE 将 sdk build 成一个 jar 包，然后手动引到 android 工程里，曲线 import

**Comment by chrisbarth01** [comment]
@FitzLu How exactly can this be done?
