### ISSUE TITLE
Could not find artifact org.ethereum:ethereumj-core error

### ISSUE THREAD

**Issue by astudnev** [bnb-chain/java-sdk#97]
Trying to install v. 1.1.0

```
[ERROR] Failed to execute goal on project binance-dex-api-client: Could not resolve dependencies for project com.binance.dex.api:binance-dex-api-client:jar:1.1.0: Could not find artifact org.ethereum:ethereumj-core:jar:1.12.0-RELEASE in central (https://repo.maven.apache.org/maven2) -> [Help 1
```

**Comment by astudnev** [comment]
I built it installing manually from https://mvnrepository.com/artifact/org.ethereum

**Comment by pellyadolfo** [comment]
The jar in maven is forbidden to me 

https://dl.bintray.com/ethereum/maven/org/ethereum/ethereumj-core/1.12.0-RELEASE/ethereumj-core-1.12.0-RELEASE.jar

even by adding the repo to the pom as in

**Comment by appfile01** [comment]
it's because bintray has been taken down and ethereumj is deprecated. someone from binance needs to sort this out, as it leaves the java sdk completely unusable rn.

**Comment by leelovejava** [comment]
https://github.com/ethereum/ethereumj/tree/1.12.0
Compile manually and install to maven repository

**Comment by appfile01** [comment]
thanks. isn't compiling well, as using older versions of all software. Will try though. Thanks!
