### ISSUE TITLE
The package named "proto" does not exist

### ISSUE THREAD

**Issue by Odiljon1994** [bnb-chain/java-sdk#99]
<img width="417" alt="Screen Shot 2020-10-10 at 3 16 55 PM" src="https://user-images.githubusercontent.com/12729350/95647641-09fcaf00-0b0c-11eb-8a26-a782323d9acf.png">

How can I deal with this problem?

**Comment by leelovejava** [comment]
https://github.com/bnb-chain/java-sdk/issues/54
